import re
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models import AppSettings
from app.schemas import PDFGenerateRequest
from app.documents._normalize import is_valid_font_size
from app.documents.pdf_generator import generate_pdf, generate_cover_letter_pdf
from app.documents.docx_generator import (
    generate_docx_resume,
    generate_docx_cover_letter,
)
from app.documents.odt_generator import (
    generate_odt_resume,
    generate_odt_cover_letter,
)
from app.section_preferences import apply_to_resume as _apply_section_prefs

router = APIRouter(prefix="/api/documents", tags=["documents"])


class CoverLetterPDFRequest(BaseModel):
    cover_letter: str
    resume_json: dict
    template: str = "modern_clean"
    font_size: str = "normal"
    hiring_manager: Optional[str] = None
    company_name: Optional[str] = None
    date: Optional[str] = None  # Client-supplied date string; uses server date if omitted
    format: str = "pdf"          # pdf | docx | odt
    inline: bool = False         # true → render inline (preview iframe), false → download


ALLOWED_TEMPLATES = {"classic_ats", "modern_clean", "executive_dark", "dark_theme"}
# Presets stay for the UI labels; numeric strings in [8.0, 13.0] also accepted
# (see is_valid_font_size). The slider sends e.g. "10.3".
ALLOWED_FONT_PRESETS = {"small", "normal", "large"}
ALLOWED_MAX_PAGES = {"1", "2", "auto"}
ALLOWED_FORMATS = {"pdf", "docx", "odt"}


_FILENAME_CLEAN = re.compile(r"[^A-Za-z0-9._-]+")


def _safe_filename(raw: str, fallback: str) -> str:
    """Strip header-injection / path-traversal chars from a downloaded filename.

    Resume JSON is generated by an LLM, so ``full_name`` can contain quotes,
    newlines, slashes, etc. that would otherwise break the Content-Disposition
    header (or worse — let a caller smuggle a second header in).
    """
    candidate = (raw or "").replace(" ", "_").lower().strip("._-")
    cleaned = _FILENAME_CLEAN.sub("", candidate)[:80]
    return cleaned or fallback


async def _load_section_prefs() -> dict | None:
    """Load saved section preferences from AppSettings (None if not set)."""
    import json as _json
    try:
        async with AsyncSessionLocal() as db:
            res = await db.execute(select(AppSettings).limit(1))
            row = res.scalar_one_or_none()
            if not row or not row.section_preferences:
                return None
            v = row.section_preferences
            if isinstance(v, str):
                try:
                    v = _json.loads(v)
                except Exception:
                    return None
            return v if isinstance(v, dict) else None
    except Exception:
        return None


FORMAT_META = {
    "pdf": (
        "application/pdf",
        "pdf",
    ),
    "docx": (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "docx",
    ),
    "odt": (
        "application/vnd.oasis.opendocument.text",
        "odt",
    ),
}


@router.post("/generate")
async def pdf_generate(req: PDFGenerateRequest):
    if req.template not in ALLOWED_TEMPLATES:
        raise HTTPException(400, f"Unknown template. Use: {ALLOWED_TEMPLATES}")
    if not is_valid_font_size(req.font_size):
        raise HTTPException(
            400,
            f"Unknown font_size. Use one of {ALLOWED_FONT_PRESETS} or a numeric pt value in [8.0, 13.0]",
        )
    if req.max_pages not in ALLOWED_MAX_PAGES:
        raise HTTPException(400, f"Unknown max_pages. Use: {ALLOWED_MAX_PAGES}")
    fmt = (req.format or "pdf").lower()
    if fmt not in ALLOWED_FORMATS:
        raise HTTPException(400, f"Unknown format. Use: {ALLOWED_FORMATS}")

    prefs = await _load_section_prefs()
    resume = _apply_section_prefs(req.resume_json, prefs) if prefs else req.resume_json

    try:
        if fmt == "pdf":
            data = generate_pdf(
                resume=resume,
                template=req.template,
                font_size=req.font_size,
                max_pages=req.max_pages,
            )
        elif fmt == "docx":
            data = generate_docx_resume(
                resume=resume,
                template=req.template,
                font_size=req.font_size,
            )
        else:
            data = generate_odt_resume(
                resume=resume,
                template=req.template,
                font_size=req.font_size,
            )
    except Exception as e:
        raise HTTPException(500, f"{fmt.upper()} generation failed: {e}")

    media_type, ext = FORMAT_META[fmt]
    raw_name = resume.get("personal_info", {}).get("full_name") or "resume"
    filename = f"{_safe_filename(raw_name, 'resume')}_{req.template}.{ext}"
    disposition = "inline" if req.inline else "attachment"

    return Response(
        content=data,
        media_type=media_type,
        headers={"Content-Disposition": f'{disposition}; filename="{filename}"'},
    )


@router.post("/cover-letter")
async def cover_letter_pdf(req: CoverLetterPDFRequest):
    if req.template not in ALLOWED_TEMPLATES:
        raise HTTPException(400, f"Unknown template. Use: {ALLOWED_TEMPLATES}")
    if not is_valid_font_size(req.font_size):
        raise HTTPException(
            400,
            f"Unknown font_size. Use one of {ALLOWED_FONT_PRESETS} or a numeric pt value in [8.0, 13.0]",
        )
    fmt = (req.format or "pdf").lower()
    if fmt not in ALLOWED_FORMATS:
        raise HTTPException(400, f"Unknown format. Use: {ALLOWED_FORMATS}")

    try:
        if fmt == "pdf":
            data = generate_cover_letter_pdf(
                cover_letter=req.cover_letter,
                resume=req.resume_json,
                template=req.template,
                font_size=req.font_size,
                hiring_manager=req.hiring_manager,
                company_name=req.company_name,
                date_str=req.date,
            )
        elif fmt == "docx":
            data = generate_docx_cover_letter(
                cover_letter=req.cover_letter,
                resume=req.resume_json,
                template=req.template,
                font_size=req.font_size,
                hiring_manager=req.hiring_manager,
                company_name=req.company_name,
                date_str=req.date,
            )
        else:
            data = generate_odt_cover_letter(
                cover_letter=req.cover_letter,
                resume=req.resume_json,
                template=req.template,
                font_size=req.font_size,
                hiring_manager=req.hiring_manager,
                company_name=req.company_name,
                date_str=req.date,
            )
    except Exception as e:
        raise HTTPException(500, f"Cover letter {fmt.upper()} generation failed: {e}")

    media_type, ext = FORMAT_META[fmt]
    raw_name = req.resume_json.get("personal_info", {}).get("full_name") or "cover_letter"
    filename = f"{_safe_filename(raw_name, 'cover_letter')}_cover_letter.{ext}"
    disposition = "inline" if req.inline else "attachment"
    return Response(
        content=data,
        media_type=media_type,
        headers={"Content-Disposition": f'{disposition}; filename="{filename}"'},
    )
